### PR TITLE
tzscan -> dunscan

### PR DESCRIPTION
**Pull request by maxtori**
- change name and filename from tzscan to dunscan
- API path for dunscan
- change tz1 example to dn1 example (except 1 that doesn't work)

### CODE REVIEW

**Comment by habanoz** [comment]
Thanks for the PR. However, it needs to be tested better. Following URLs are not correct.

{'MAINNET': {'API_URL': 'http://api.dunscan.io/v3/head'},
                     'ALPHANET': {'API_URL': 'http://api.testnet.dunscan.io/v3/head'},	                     'TESTNET': {'API_URL': 'http://api%MIRROR%.testnet.dunscan.io/v3/head'},
                     'ZERONET': {'API_URL': 'http://api.zeronet.dunscan.io/v3/head'}	                     'DEVNET': {'API_URL': 'http://api.devnet.dunscan.io/v3/head'}
                     }	                     }

**Comment by maxtori** [comment]
Hi, 
I am part of the dunscan team, these are the right paths for the API (mainnet, testnet, devnet), except devnet that we haven't launched publicly yet.
I haven't tested the code either, I was thinking that you were more able than me to see if they were mistakes.

**Comment by cagdasbozman** [comment]
@habanoz what's wrong with the URLs ?
URLs for dunscan are :
 - mainnet : api.dunscan.io
 - testnet : api{1,2,3,4,5,6}.testnet.dunscan.io
- no public devnet yet

Do you know how can we test it quickly ? I know some of bakers on Dune that will be glad to help you run some tests.

**Comment by habanoz** [comment]
It should be :
http://api{1,2,3,4,5,6}.dunscan.io
http://api.testnet.dunscan.io

It is already set to this form in the code. Proposed PR is not correct at this point. I cannot accept this PR this way. 

Please check the contribution guide. 
https://github.com/habanoz/tezos-reward-distributor/wiki/How-to-Contribute

**Comment by maxtori** [comment]
Hi, it is now rebased.
I understand that everything in the PR is not to be kept, but the API paths are important and since we are the developers of dunscan we are well placed to tell you that they are the correct paths...
http://api1.dunscan.io works right now but since we are doing some load balancing using the address
http://api.dunscan.io we would prefer that you use this one, same for http://api.testnet.dunscan.io, it works but it is a back end for http://api1.testnet.dunscan.io.
These paths will probably not be kept in the future.

**Comment by habanoz** [comment]
Introduction of LB was not clear at the first glance. Thanks for clarifying.

Still there are some dead wiki links but I am merging the PR. 

One question:

Are there any dunescan public rpc services.

**Pull request merged**
